export const ListFooter = [
    {
        id:1,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:2,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:3,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:4,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:5,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:6,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:7,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:8,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:9,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:10,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:11,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:12,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:13,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },
    {
        id:14,
        name:'Introduce',
        link:'/',
        tag:'introduce',
    },

]